### ISSUE TITLE
Links to download the datasets

### ISSUE THREAD

**Issue by kenchan0226** [yumoxu/lqsum#1]
Hi, thanks for the excellent work. 
I would like to ask if there is any link to download the datasets and the pre-trained checkpoints?

**Comment by yumoxu** [comment]
Hi @kenchan0226, thanks for your interest in our work. The datasets and pre-trained checkpoints are now being prepared and will be released next week, stay tuned!

**Comment by yuulin** [comment]
> Hi @kenchan0226, thanks for your interest in our work. The datasets and pre-trained checkpoints are now being prepared and will be released next week, stay tuned!

Hi, are datasets and pre-trained checkpoints prepared now?
